version: '3'

services:
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    networks:
      - uanetwork
    ports:
      - 6379:6379
    volumes:
      - redis:/data

networks:
  uanetwork:
    name: uanetwork

volumes:
  redis:
    driver: local  